Adopt code for Khalani Protocol
tvl-labs/faucet pull request #1
Opened 2023-05-16 13:50 UTC by serejke

This PR contains the patches on top of the origin Avalanche Faucet that adopt for Khalani protocol:
- allow to configure faucet from a file specified by `CONFIG_FILE`
- allow to override RPC URLs with ENV variables of name `EVM_CHAINS_${ID}_RPC`, where `ID` is the chain ID specified in `evmchains` of `config.json`, for example `EVM_CHAINS_KHALANITESTNET_RPC`
- allow to disable captcha verification — needed to test the deployment and then register Google Captcha for the production domain
- added Khalani Protocol branding (logo / docs)
- GitHub pipeline to build a Docker image

2023-05-16 15:43 UTC, Kuzirashi approved these changes

2023-05-16 21:00 UTC, samtvlabs requested changes
This need to be modified to `Add chain to Metamask`, as subnets are an avalanche specific thing

2023-05-16 21:00 UTC, distributedstatemachine commented on .env.dist
> +DISABLE_CAPTCHA=true
Why are you disabling captcha ? Faucets get DDOSed (tbh its a nice problem for us to have at this point ) . I would like to understand the intuition behind this

2023-05-16 21:00 UTC, distributedstatemachine commented on client/public/index.html
> +    <meta name="description" content="Get testnet tokens to use for the Khalani Protocol (USDC/USDT testnet tokens on Khalani chain, Goerli, Avalanche Fuji, etc) in one place.">
Do you want to take out chain specific details  `USDC/USDT testnet tokens on Khalani chain, Goerli, Avalanche Fuji, etc` and replace it with something along the lines of "Testnet tokens to interact with the Khalani protocol"

2023-05-16 21:00 UTC, distributedstatemachine commented on client/public/index.html
> +    <meta property="og:description" content="Get testnet tokens to use for the Khalani Protocol (USDC/USDT testnet tokens on Khalani chain, Goerli, Avalanche Fuji, etc) in one place.">
Same as above

2023-05-16 21:04 UTC, samtvlabs commented on .env.dist
> +DISABLE_CAPTCHA=true
seen this : 

> - allow to disable captcha verification — needed to test the deployment and then register Google Captcha for the production domain

2023-05-18 10:40 UTC, serejke commented
- significantly streamlined the state management of requests and nonce/balance recalibration
- added support of faucet wallet signer with [AWS KMS](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html)
- added Prometheus support

2023-05-25 16:11 UTC, KonraddB reviewed
I compared the source code with the refactored code and did not find any potential issues. However, by the way, a few cosmetic issues have been reported.

2023-05-25 16:11 UTC, konraddb commented on server.ts
> +    router.get('/faucetAddress', async (req: any, res: any) => {
no need 'async' here

2023-05-25 16:11 UTC, konraddb commented on server.ts
> +        const balance = evm.getBalance(id);
In the source code, when there is no balance, their are using `balance = new BN(0)`

2023-05-25 16:11 UTC, KonraddB commented on client/public/banner.jpeg
Can we perhaps use a logo here with a transparent background and of better quality?

2023-06-03 09:26 UTC, samtvlabs commented
@serejke is this good to go?

2023-06-09 10:03 UTC, merged

2023-06-09 10:04 UTC, serejke commented
Merged 🚀